#!/usr/bin/env python3
"""
# Input files:
#   - Most recent audit_reports/pdf_link_flattened_audit_*_summary.csv when present,
#     otherwise most recent audit_reports/*_summary.csv
#     in visualizer_nlp_lit_review/audit_reports/
#   - visualizer_nlp_lit_review/RIS_source_files/manual_groupings/pdf_overrides.json
#
# Output files:
#   - visualizer_nlp_lit_review/RIS_source_files/manual_groupings/pdf_overrides.json
#     (only when --mark-bad is used; updated in place)
#
# Generated by: review_pdf_queue.py

Interactive review helper for suspected PDF mismatches.

Reads an existing flattened audit CSV, filters rows by classification, and
prints a human-readable review queue. Optionally extracts first-page PDF text
for side-by-side comparison.

Usage examples
--------------
Show 20 likely_mismatch rows starting at offset 0 with first-page text:

    python3 visualizer_nlp_lit_review/scripts/review_pdf_queue.py \\
        --classification likely_mismatch --show-text

Page through manual_review rows:

    python3 visualizer_nlp_lit_review/scripts/review_pdf_queue.py \\
        --classification manual_review --limit 10 --offset 10

Mark a confirmed bad PDF path (updates pdf_overrides.json):

    python3 visualizer_nlp_lit_review/scripts/review_pdf_queue.py \\
        --mark-bad "internal-pdf://1953443372/Extracting Pulmonary Embolism Dia-Mahyoub-2025.pdf"
"""
from __future__ import annotations

import argparse
import csv
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import List, Optional

VISUALIZER_DIR = Path(__file__).resolve().parents[1]
AUDIT_REPORTS_DIR = VISUALIZER_DIR / "audit_reports"

if str(VISUALIZER_DIR) not in sys.path:
    sys.path.insert(0, str(VISUALIZER_DIR))

from pdf_overrides import load_pdf_overrides, save_pdf_overrides


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def find_latest_summary_csv() -> Optional[Path]:
    """Return the preferred summary CSV for review work.

    Full flattened audits are preferred over small smoke-test audit outputs
    because smoke tests use the same suffix and can otherwise become the
    newest file by mtime.
    """
    flattened = sorted(
        AUDIT_REPORTS_DIR.glob("pdf_link_flattened_audit_*_summary.csv"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    if flattened:
        return flattened[0]

    candidates = sorted(
        AUDIT_REPORTS_DIR.glob("*_summary.csv"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    return candidates[0] if candidates else None


def load_audit_rows(csv_path: Path, classifications: List[str]) -> List[dict]:
    """Load CSV rows whose classification matches one of the given values."""
    with open(csv_path, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    if classifications:
        rows = [r for r in rows if r.get("classification") in classifications]
    return rows


def extract_first_page_text(resolved_pdf: str, pages: int = 3) -> str:
    """Run pdftotext on the resolved local path; return text or error message."""
    if not resolved_pdf:
        return "(no local path resolved)"
    if not Path(resolved_pdf).exists():
        return f"(file not found: {resolved_pdf})"
    if shutil.which("pdftotext") is None:
        return "(pdftotext not installed)"
    with tempfile.NamedTemporaryFile(suffix=".txt", delete=False) as out:
        out_name = out.name
    cmd = [
        "pdftotext",
        "-f", "1",
        "-l", str(max(1, min(3, pages))),
        "-layout",
        resolved_pdf,
        out_name,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=30, check=False)
    if result.returncode != 0:
        return f"(pdftotext error: {(result.stderr or result.stdout or '').strip()[:200]})"
    text = Path(out_name).read_text(encoding="utf-8", errors="ignore")
    Path(out_name).unlink(missing_ok=True)
    # Return first ~60 non-empty lines
    lines = [l for l in text.splitlines() if l.strip()][:60]
    return "\n".join(lines)


def print_row(idx: int, total: int, row: dict, show_text: bool) -> None:
    cls = row.get("classification", "")
    print(f"\n{'─' * 72}")
    print(f"[{idx}/{total}] {cls}")
    print(f"  Title  : {row.get('title', '')}")
    print(f"  DOI    : {row.get('doi', '')}")
    print(f"  PMID   : {row.get('pmid', '')}")
    author = row.get('first_author', '')
    year = row.get('year', '')
    print(f"  Author : {author} ({year})")
    print(f"  Key    : {row.get('paper_key', row.get('paper_id', ''))}")
    print(f"  PDF    : {row.get('pdf_path', '')}")
    resolved = row.get("resolved_pdf", row.get("resolved_pdf_path", ""))
    print(f"  Local  : {resolved or '(not resolved)'}")
    score = row.get("score", "")
    overlap = row.get("title_token_overlap", "")
    doi_p = row.get("doi_present", "")
    auth_p = row.get("first_author_present", row.get("first_author_surname_present", ""))
    print(f"  Score  : {score}  overlap={overlap}  doi={doi_p}  author={auth_p}")
    candidate = row.get("candidate_pdf_title_line", row.get("best_line", ""))
    if candidate:
        print(f"  CandTitle: {candidate[:120]}")
    error = row.get("error", "")
    if error:
        print(f"  Error  : {error}")
    if show_text:
        text = extract_first_page_text(resolved)
        print(f"  {'─' * 66}")
        for line in text.splitlines()[:40]:
            print(f"    {line}")


# ---------------------------------------------------------------------------
# --mark-bad
# ---------------------------------------------------------------------------

def mark_bad(pdf_path: str) -> None:
    """Append pdf_path to bad_pdf_paths in pdf_overrides.json (idempotent)."""
    data = load_pdf_overrides()
    existing: list = data.get("bad_pdf_paths", [])
    existing_set = set(existing)
    if pdf_path in existing_set:
        print(f"Already suppressed: {pdf_path}")
        return
    existing_set.add(pdf_path)
    data["bad_pdf_paths"] = sorted(existing_set)
    save_pdf_overrides(data)
    print(f"Suppressed: {pdf_path}")
    print(f"Total bad_pdf_paths: {len(data['bad_pdf_paths'])}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Review suspected PDF mismatch queue from audit CSV.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--classification",
        action="append",
        dest="classifications",
        metavar="CLASS",
        choices=[
            "likely_mismatch",
            "manual_review",
            "unreadable_pdf",
            "weak_match",
            "ok",
            "missing_pdf",
            "suppressed_by_override",
            "replaced_by_override",
        ],
        help="Classification(s) to include. Repeatable. Default: likely_mismatch",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=20,
        help="Max rows to show (default 20). 0 = show all.",
    )
    parser.add_argument(
        "--offset",
        type=int,
        default=0,
        help="Skip first N matching rows (default 0).",
    )
    parser.add_argument(
        "--show-text",
        action="store_true",
        help="Extract and print first-page PDF text for each row.",
    )
    parser.add_argument(
        "--mark-bad",
        metavar="PDF_PATH",
        help="Append PDF_PATH to bad_pdf_paths in pdf_overrides.json and exit.",
    )
    parser.add_argument(
        "--csv",
        metavar="PATH",
        help="Path to audit summary CSV. Default: newest flattened audit, else newest summary.",
    )
    args = parser.parse_args()

    if args.mark_bad:
        mark_bad(args.mark_bad)
        return 0

    csv_path = Path(args.csv) if args.csv else find_latest_summary_csv()
    if csv_path is None:
        print("ERROR: No audit summary CSV found in audit_reports/. Run audit_pdf_links.py first.", file=sys.stderr)
        return 1
    if not csv_path.exists():
        print(f"ERROR: CSV not found: {csv_path}", file=sys.stderr)
        return 1

    classifications = args.classifications or ["likely_mismatch"]
    rows = load_audit_rows(csv_path, classifications)
    total_matching = len(rows)

    rows = rows[args.offset:]
    if args.limit:
        rows = rows[: args.limit]

    if not rows:
        print(f"No rows found for classification(s) {classifications} at offset {args.offset}.")
        return 0

    print(f"Source : {csv_path.name}")
    print(f"Filter : {classifications}  total={total_matching}  offset={args.offset}  showing={len(rows)}")

    for i, row in enumerate(rows, start=1):
        print_row(args.offset + i, total_matching, row, args.show_text)

    print(f"\n{'─' * 72}")
    print(f"Showing {len(rows)} of {total_matching} rows.")
    print("To suppress a bad PDF:")
    print('  python3 visualizer_nlp_lit_review/scripts/review_pdf_queue.py \\')
    print('    --mark-bad "<pdf_path>"')
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
