#!/usr/bin/env python3
"""
Tests for the explicit-label RN stamper.

Inputs:
- tests/fixtures/five_refs.ris

Outputs:
- None permanent (tmp_path).

Run with:
    cd automated_search && python3 -m pytest tests/test_label_explicit.py
"""

import sys
from pathlib import Path

import pytest

HELPERS = Path(__file__).resolve().parents[1] / "scripts" / "helpers"
if str(HELPERS) not in sys.path:
    sys.path.insert(0, str(HELPERS))

from label_papers_w_search_terms_v2 import (  # type: ignore[import-not-found]
    add_research_notes_to_ris_with_explicit_label,
)

FIXTURE_RIS = Path(__file__).resolve().parent / "fixtures" / "five_refs.ris"


def test_explicit_label_stamps_every_entry(tmp_path):
    out = tmp_path / "labeled.ris"
    add_research_notes_to_ris_with_explicit_label(FIXTURE_RIS, out, "( smoke )")
    text = out.read_text(encoding="utf-8")
    assert text.count("ER  - ") == 5 or text.count("ER  -") == 5
    rn_count = sum(1 for line in text.splitlines() if line.startswith("RN  - ( smoke )"))
    assert rn_count == 5


def test_explicit_label_replaces_existing_rn(tmp_path):
    src = tmp_path / "with_rn.ris"
    src.write_text(
        "TY  - JOUR\n"
        "AU  - Doe, J\n"
        "TI  - X\n"
        "AN  - 11111111\n"
        "RN  - old_label\n"
        "ER  - \n",
        encoding="utf-8",
    )
    out = tmp_path / "out.ris"
    add_research_notes_to_ris_with_explicit_label(src, out, "(new)")
    text = out.read_text(encoding="utf-8")
    assert "old_label" not in text
    assert "RN  - (new)" in text


def test_explicit_label_rejects_empty(tmp_path):
    out = tmp_path / "x.ris"
    with pytest.raises(ValueError, match="non-empty"):
        add_research_notes_to_ris_with_explicit_label(FIXTURE_RIS, out, "")


def test_explicit_label_writes_generator_comment(tmp_path):
    out = tmp_path / "x.ris"
    add_research_notes_to_ris_with_explicit_label(FIXTURE_RIS, out, "(test)")
    head = out.read_text(encoding="utf-8").splitlines()[0]
    assert "generated by" in head
    assert "label_papers_w_search_terms_v2.py" in head
